INSERT INTO authors (name, url_name, birth_year, death_year, biography) VALUES
('Apulée', 'apulee', 125, 180, 'Philosophe et écrivain berbère romain, célèbre pour son roman "Les Métamorphoses" ou "L’Âne d’or".'),
('Aulu-Gelle','aulu-gelle', 125, 180, 'Grammairien et compilateur romain, connu pour ses "Nuits Attiques", un recueil d’anecdotes et de savoirs.'),
('Aurelius Victor', 'aurelius-victor', 320, 390, 'Historien romain, auteur de "De Caesaribus", une série de biographies des empereurs romains.'),
('Ausone', 'ausone', 310, 395, 'Poète et professeur bordelais, célèbre pour ses poèmes et son influence à la cour impériale.'),
('Avianus', 'avianus', 400, 450, 'Fabuliste latin tardif, connu pour ses adaptations en vers des fables d’Ésope.'),
('Calpurnius Siculus', 'calpurnius-siculus', 40, 70, 'Poète pastoral romain, auteur de "Bucoliques", inspirées de Virgile.'),
('Catulle', 'catulle', -84, -54, 'Poète lyrique de la fin de la République romaine, célèbre pour ses poèmes passionnés et satiriques.'),
('Celse', 'celse', 25, 50, 'Médecin et encyclopédiste romain, auteur du traité médical "De Medicina".'),
('Censorinus', 'censorinus', 200, 250, 'Grammairien romain, connu pour son ouvrage "De Die Natali", traitant de chronologie et de sciences.'),
('César', 'cesar', -100, -44, 'Général et homme politique romain, auteur des "Commentaires sur la Guerre des Gaules".'),
('Cicéron', 'ciceron', -106, -43, 'Orateur, homme d’État et philosophe romain, célèbre pour ses discours et ses traités philosophiques.'),
('Claudien', 'claudien', 370, 404, 'Poète de cour à la fin de l’Empire romain, auteur de poèmes politiques et mythologiques.'),
('Commodien', 'commodien', 250, 300, 'Poète chrétien latin, connu pour ses poèmes moraux en vers acéphales.'),
('Columelle', 'columelle', 4, 70, 'Agronome romain, auteur du traité "De Re Rustica" sur l’agriculture.'),
('Cornelius Nepos', 'cornelius-nepos', -100, -25, 'Biographe romain, célèbre pour ses "Vies des hommes illustres".'),
('Corippe', 'corippe', 500, 550, 'Poète épique latin d’Afrique du Nord, auteur de "Johannis" et "In laudem Justini".'),
('Eutrope', 'eutrope', 320, 390, 'Historien romain, auteur du "Breviarium Historiae Romanae", un abrégé de l’histoire romaine.'),
('Florus', 'florus', 70, 140, 'Historien romain, connu pour son "Epitome de l’histoire romaine".'),
('Frontin', 'frontin', 40, 103, 'Ingénieur et écrivain romain, auteur de "De aquaeductu", traité sur les aqueducs de Rome.'),
 ('Grattius Faliscus', 'grattius-faliscus', -63, 14, 'Poète romain, auteur du poème didactique "Cynegetica" sur la chasse.'),
 ('Histoire Auguste', 'histoire-auguste', 300, 400, 'Recueil de biographies d’empereurs romains, d’auteurs anonymes du IVe siècle.'),
 ('Horace', 'horace', -65, -8, 'Poète lyrique romain, célèbre pour ses "Odes" et "Satires".'),
 ('Julius Obsequens', 'julius-obsequens', 350, 400, 'Auteur romain, compilateur de prodiges et phénomènes célestes.'),
 ('Justin', 'justin', 100, 165, 'Historien romain, auteur d’un abrégé de l’histoire universelle de Trogue Pompée.'),
 ('Juvénal', 'juvenal', 55, 140, 'Poète satirique romain, connu pour ses "Satires" dénonçant les mœurs de son temps.'),
 ('Lactance', 'lactance', 250, 325, 'Auteur chrétien latin, surnommé le "Cicéron chrétien", auteur des "Institutions divines".'),
 ('Lucain', 'lucain', 39, 65, 'Poète épique romain, auteur de la "Pharsale", récit de la guerre civile entre César et Pompée.'),
 ('Lucrèce', 'lucrece', -99, -55, 'Poète et philosophe romain, auteur du poème "De rerum natura" sur l’épicurisme.'),
('Macrobe', 'macrobe', 370, 430, 'Philosophe et grammairien romain, connu pour ses "Saturnales" et son commentaire sur Cicéron.'),
('Manilius', 'manilius', -10, 20, 'Poète romain, auteur de "Astronomica", poème didactique sur l’astrologie.'),
 ('Martial', 'martial', 40, 104, 'Poète romain, célèbre pour ses "Épigrammes" satiriques.'),
 ('Julius Firmicus Maternus', 'julius-firmicus-maternus', 300, 360, 'Auteur romain, connu pour ses ouvrages sur l’astrologie et la religion chrétienne.'),
('Minucius Felix', 'minucius-felix', 150, 250, 'Apologiste chrétien latin, auteur du dialogue "Octavius".'),
('Ovide', 'ovide', -43, 17, 'Poète romain, célèbre pour ses "Métamorphoses" et son exil à Tomis.'),
('Palladius', 'palladius', 350, 420, 'Agronome romain, auteur de "Opus agriculturae", manuel d’agriculture.'),
 ('Perse', 'perse', 34, 62, 'Poète satirique romain, connu pour ses "Satires" morales.'),
 ('Pétrone', 'petrone', 27, 66, 'Écrivain romain, auteur du "Satyricon", roman satirique.'),
 ('Phèdre', 'phedre', 15, 50, 'Fabuliste romain, auteur de fables inspirées d’Ésope.'),
('Plaute', 'plaute', -254, -184, 'Dramaturge romain, célèbre pour ses comédies influencées par le théâtre grec.')